services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    env_file:
      - ./.env
      - ../../.env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
    ports:
      - ${TRANSMISSION_HOST_PORT}:9091 # webui for Transmission - it is exposed via the docker service network internally
      - ${TRANSMISSION_SEED_DISCOVERY_PORT_TCP}:51413 # for seed discovery - greatly improves performance even if not seeding
      - ${TRANSMISSION_SEED_DISCOVERY_PORT_UDP}:51413/udp
      - ${DUPLICATI_HOST_PORT}:8200
    networks:
      - homelab
    restart: unless-stopped
    profiles:
      - all
      - vpn
